name: hyperbolic-gmra
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8.*
  - pip
  - setuptools
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pytorch=2.3.1
  - torchvision
  - cudatoolkit=11.8
  - cudnn
  - tensorflow
  - tensorboard
  - keras
  - h5py
  - pillow
  - tqdm
  - networkx
  - pyyaml
  - sympy
  - mpmath
  - gmpy2
  - flask
  - jinja2
  - requests
  - urllib3
  - cryptography
  - pysocks
  - filelock
  - cmake
  - ninja
  - mkl
  - blas
  - openblas
  - lapack
  - gmp
  - mpfr
  - mpc
  - fftw
  - hdf5
  - zlib
  - bzip2
  - xz
  - libpng
  - freetype
  - libtiff
  - jpeg
  - openjpeg
  - libwebp
  - lcms2
  - zstd
  - libcurl
  - openssl
  - krb5
  - libssh2
  - libxml2
  - icu
  - readline
  - ncurses
  - sqlite
  - tk
  - libuuid
  - expat
  - fontconfig
  - ca-certificates